version: "3.5"

services:
  app:
    container_name: skynet-app
    build:
      context: docker/app
      target: development
    volumes:
      - ./public:/var/www/html/public
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - skynet

  mysql.database:
    image: mysql
    container_name: skynet-database
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - skynet

  adminer:
    image: adminer
    container_name: skynet-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql.database
    ports:
      - 8080:8080
    depends_on:
      - mysql.database
    networks:
      - skynet
networks:
  skynet:
    driver: "bridge"